# use `UID="$(id -u)" GID="$(id -g)" docker-compose up --build` to run a local version of the api
version: '3.3'
services:
  streamflow-api:
    user: "${UID}:${GID}"
    build:
      context: ".."
      dockerfile: api/Dockerfile
      args:
        UID: "$UID"
        GID: "$GID"
    environment:
      STREAMFLOW.MODE: "dev"
      STREAMFLOW.TASKS_TABLE_NAME: "streamflow_tasks"
      STREAMFLOW.TASKS_RUNS_TABLE_NAME: "streamflow_task_runs"
      STREAMFLOW.TASK_STREAM_NAME: "task_message_stream"  # todo add in tf
      AWS_DEFAULT_REGION: "$AWS_DEFAULT_REGION"
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - $HOME/.aws/:/home/streamflow/.aws/:ro
      - ..:/local-src
    working_dir: /local-src
    command: bash -c "cp /streamflow-backend/main_api.py /local-src && uvicorn main_api:app --reload --host 0.0.0.0 --port 8080"