# use `UID="$(id -u)" GID="$(id -g)" docker-compose up --build` to run a local version of the api
version: '3.3'
services:
  streamflow-orchestrator:
    user: "${UID}:${GID}"
    build:
      context: ".."
      dockerfile: Dockerfile
      args:
        UID: "$UID"
        GID: "$GID"
    environment:
      STREAMFLOW__MODE: "dev"
      AWS_DEFAULT_REGION: "$AWS_DEFAULT_REGION"
    restart: on-failure
    volumes:
      - $HOME/.aws/:/home/streamflow/.aws/:ro
      - ..:/local-src
    working_dir: /local-src
    command: bash -c "python /local-src/cli.py orchestrator start"
